### ISSUE TITLE
Integracja GitHub z Discordem z dedykowanym kanałem

### ISSUE THREAD

**Issue by vault51** [gftlmag/rampage#7]
- wysyłanie notyfikacji po WebHookach

?? może Zapier

**Comment by HalinSky** [comment]
TEST: Integracja GitHub bota z discordem. (czy wysyła wiadomość gdy zostanie dodany komentarz do issue)

**Comment by HalinSky** [comment]
TEST: Integracja GitHub bota z discordem. (czy wysyła wiadomość gdy zostanie dodany komentarz do issue)

**Comment by HalinSky** [comment]
[+] Added #notifactions discord channel at Lmag! server
[+] Created discord webhook for channel
[+] Added github webhook connection for all notifactions

NOTE: Improvements might appear later. Currently as is.
